version: '3.9'

services:
  server:
    image: 'timeenjoyed/codejam:latest'
    container_name: codejam_backend
    build: .
    volumes:
      - ./backend/app/config.toml:/app/config.toml
    ports:
      - '8080:8080'

  database:
    image: 'library/postgres:16.3-alpine3.20'
    container_name: codejam_database

  redis:
    image: 'library/redis:7.0.15-alpine3.20'
    container_name: codejam_redis
