version: '3.9'

services:
  database:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: codejam
    volumes:
      - './docker/postgres/:/var/lib/postgresql/data'
