[server]
listen = "0.0.0.0:8080"

[database]
url = "postgres://username:password@127.0.0.1:5432/database"
maxconnections = 16

[github]
# for OAuth
id = ""
secret = ""
redirectUrl = "http://localhost/oauth/callback"
